=== jesimone57/spring_boot_scala_rest_example/src/main/resources/sample1_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Fee update schema",
  "uniqueItems": true,
  "minItems": 1,
  "items":  {
    "properties": {
      "idStr": {
        "type": "string",
        "description": "Fee code id"
      },
      "label": {
        "description": "Fee code name",
        "type": "string",
        "minLength": 1,
        "maxLength": 100,
        "pattern":  "^[a-zA-Z0-9]{1,100}$"
      },
      "fee": {
        "type": "number",
        "minimum": 0,
        "maximum": 99999.99,
        "multipleOf":  0.01
      },
      "earlyFee": {
        "type": "number",
        "minimum": 0,
        "maximum": 99999.99,
        "multipleOf": 0.01
      },
      "lateFee": {
        "type": "number",
        "minimum": 0,
        "maximum": 99999.99,
        "multipleOf": 0.01
      },
      "feeScope": {
        "description": "Fee scope",
        "type": "string",
        "enum": [
          "REGISTRANTS",
          "GUESTS",
          "BOTH"
        ]
      },
      "selected": {
        "type": "boolean"
      },
      "restrictedAccess": {
        "type": "boolean"
      }
    },
    "required": [ "idStr", "label", "fee", "earlyFee", "lateFee", "feeScope", "restrictedAccess"],
    "additionalProperties": false
  }
}

=== jesimone57/spring_boot_scala_rest_example/src/main/resources/sample1.json
[
  {
    "idStr": "a7fc-7b",
    "label": "AmusementDiscount07",
    "fee": 12.50,
    "earlyFee": 12.50,
    "lateFee": 12.50,
    "feeScope": "REGISTRANTS",
    "selected": true,
    "restrictedAccess": false
  },
  {
    "idStr": "a7fc-7c",
    "label": "AmusementDiscount08",
    "fee": 12.50,
    "earlyFee": 12.50,
    "lateFee": 12.50,
    "feeScope": "GUESTS",
    "selected": false,
    "restrictedAccess": false
  },
  {
    "idStr": "b8da-14",
    "label": "FoodCourtDiscount17",
    "fee": 12.50,
    "earlyFee": 12.50,
    "lateFee": 12.50,
    "feeScope": "BOTH",
    "restrictedAccess": false
  }
]
